### PR TITLE
- Implementing new bathroom layout

### PR DESCRIPTION
**Pull request by ghost**
`NOTE Original UI is still in place, we can strip it out once this PR has been merged and tested.`
- Added svg for mens room and broke apart css
- Handled responsiveness
  - Landscape view of floor in desktop and tablet resolutions
  - Portrait view of floor for anything smaller than tablet
  - Floor map animates - rotates and scales based on resolution
- handled occupied and open states
  - Open
    - Stall is green
    - Door is open
  - 'Occupied'
    - Stall is red
    - Door is closed
    - Animation of Urinal 'swell' (scales larger and smaller on a loop)

### CODE REVIEW

**Comment by ghost** [comment]
I think the conflict below is related to the compiled master.css. I believe this should be un-tracked and not commited, and we could have the build process generate it. Let me know what you think and we can talk that through...

**Comment by dasavi** [comment]
@befreestudios Totally agree. Do you want to do that as part of this PR or should we do it separately?

**Comment by ghost** [comment]
@dasavi We could do it separately, if thats cool with you. (Don't really have time to look into it at the moment :P )

**Comment by dasavi** [comment]
@befreestudios Works for me. I'll just yolo merge this in and we can figure it out later.

**Comment by ghost** [comment]
@dasavi

**Pull request merged**
